name: tus_client_dart
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 2.4.0
homepage: https://github.com/tomassasovsky/tus_client

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cross_file: ^0.3.3+1
  http: ^0.13.4
  speed_test_dart: ^1.0.2

dev_dependencies:
  mockito: ^5.2.0
  build_runner: ^2.1.11
  test: ^1.21.1
